version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: kasrevent
      POSTGRES_PASSWORD: kasrevent
      POSTGRES_DB: kasrevent
    ports:
      - "5432:5432"
    volumes:
      - kasrevent_pgdata:/var/lib/postgresql/data

volumes:
  kasrevent_pgdata:
